version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "brain-tasks-app"
Hooks:
  AfterAllowTestTraffic:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
